apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-site
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-site
  template:
    metadata:
      labels:
        app: flask-site
    spec:
      containers:
      - name: flask
        image: us.icr.io/brandynlabs/flask-site:latest #change this to personal namespace
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"

#Creates a Deployment that creates 3 pods running identical copies of the Flask for load balancing/reliabilty.
#Determines container specifics and pod naming labels.


---
apiVersion: v1
kind: Service
metadata:
  name: flask-site-svc
spec:
  type: NodePort
  ports:
  - port: 80 
    targetPort: 8080
    nodePort: 30080
  selector:
    app: flask-site
# Creates a Service that exposes the app on port 30080 of every worker node
# Traffic to port 30080 â†’ forwarded to port 8080 on the pods
# Port 80 is the internal Service port
